import json
import datetime
import os
import sys

# To support running directly
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from dedup.dedup_engine import run_dedup
from events.cluster_events import run_clustering
from events.event_scoring import score_event
from anchors.build_top_story_anchors import build_anchors
from anchors.anchor_similarity import match_event_to_anchor
from angles.select_angles import select_angles
from ranking.rank_events import rank_events
from ranking.select_buckets import select_buckets

def load_json(filepath, default=None):
    if not os.path.exists(filepath):
        return default
    with open(filepath, 'r') as f:
        return json.load(f)

def save_json(data, filepath):
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, 'w') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

def main():
    print("Building Insight Digest...")

    # 1. read insight_latest.json
    latest = load_json("public/newsdata/insight_latest.json", {"stories": []})
    stories = latest.get("stories", [])
    if not stories:
        print("No stories found.")
        return

    # 2. run_dedup
    dedup_res = run_dedup(stories)
    deduped_stories = dedup_res["stories"]
    diagnostics = dedup_res["diagnostics"]

    # 3. build_event_clusters
    events = run_clustering(deduped_stories)
    events = [score_event(e) for e in events]
    diagnostics["clusterCount"] = len(events)

    # 4. build_top_story_anchors
    anchors_payload = build_anchors(deduped_stories)
    anchors = anchors_payload["anchors"]
    diagnostics["anchorCount"] = len(anchors)

    # 5. attach_anchor_matches
    storiesById = {s['id']: s for s in deduped_stories}
    anchorMatchedParentCount = 0
    for ev in events:
        a_id, score, reasons = match_event_to_anchor(ev, anchors)
        ev["topStoryAnchorId"] = a_id
        ev["topStoryAnchorScore"] = score
        ev["topStoryAnchorBand"] = "strong" if score >= 0.78 else "acceptable" if score >= 0.62 else "weak"
        ev["anchorMatchReasons"] = reasons
        if score >= 0.62:
            anchorMatchedParentCount += 1
    diagnostics["anchorMatchedParentCount"] = anchorMatchedParentCount

    # 6. attach_angles_to_events
    angleDistribution = {}
    for ev in events:
        cluster_stories = [storiesById[sid] for sid in ev["storyIds"] if sid in storiesById]
        angles = select_angles(cluster_stories, ev)
        ev["angles"] = angles
        for a in angles:
            angleDistribution[a['angle']] = angleDistribution.get(a['angle'], 0) + 1

    diagnostics["angleDistribution"] = angleDistribution

    # 7. select_insight_buckets
    ranked = rank_events(events)
    diagnostics["rankedParentCount"] = len(ranked)
    selected_events = select_buckets(ranked)
    diagnostics["selectedParentCount"] = len(selected_events)
    diagnostics["weakParentCount"] = 0
    diagnostics["droppedWeakParentCount"] = 0
    diagnostics["sourceDistribution"] = {}

    # 8. convert to digest cards
    cards = []
    for ev in selected_events:
        cards.append({
            "eventId": ev["eventId"],
            "bucket": ev["bucket"],
            "headline": ev["canonicalHeadline"],
            "summary": ev["canonicalSummary"],
            "whyItMatters": "This is important context generated by the workflow.",
            "score": ev["eventScore"],
            "coverageLabel": "Good coverage",
            "sourceCount": len(ev["sourceGroups"]),
            "independentSourceCount": ev["independentSourceCount"],
            "hiddenDuplicateCount": len(ev.get("hiddenDuplicateIds", [])),
            "topStoryAnchorId": ev.get("topStoryAnchorId"),
            "topStoryAnchorScore": ev.get("topStoryAnchorScore", 0),
            "topStoryAnchorBand": ev.get("topStoryAnchorBand"),
            "snapshotPresence": ev.get("snapshotPresence", {}),
            "angles": ev.get("angles", []),
            "selectionReasons": [],
            "scoreBreakdown": ev.get("scoreBreakdown", {})
        })

    digest = {
        "schemaVersion": "2.0.0",
        "generatedAt": datetime.datetime.utcnow().isoformat() + "Z",
        "sourceMode": "github-workflow",
        "diagnosticsRef": "insight_diagnostics.json",
        "sourceHealthRef": "insight_source_health.json",
        "cards": cards
    }

    # 9-11. Write files
    save_json(anchors_payload, "public/newsdata/top_story_anchors.json")
    save_json(digest, "public/newsdata/insight_digest.json")
    save_json(diagnostics, "public/newsdata/insight_diagnostics.json")

    print("Digest build complete.")

if __name__ == "__main__":
    main()
