import React, { createContext, useContext, useState, useCallback, useEffect } from 'react';
import { fetchAllMarketData } from '../services/indianMarketService';
import { idbGet, idbSet } from '../utils/idb';

const MarketContext = createContext(null);
/* eslint-disable react-refresh/only-export-components */

const CACHE_KEY = 'market_cache';
const CACHE_DURATION = 15 * 60 * 1000; // 15 minutes

export function MarketProvider({ children }) {
    const [marketData, setMarketData] = useState(null);
    const [loading, setLoading] = useState(true);  // Keep true — prevents flash-of-empty (audit v3 fix)
    const [error, setError] = useState(null);
    const [lastFetch, setLastFetch] = useState(null);
    const [booted, setBooted] = useState(false);

    const loadMarketData = useCallback(async (forceRefresh = false) => {
        // Check cache first
        if (!forceRefresh) {
            try {
                let parsed = await idbGet(CACHE_KEY);
                if (!parsed) {
                    const cached = localStorage.getItem(CACHE_KEY);
                    if (cached) {
                        parsed = JSON.parse(cached);
                        idbSet(CACHE_KEY, parsed); // migrate to IDB
                    }
                }

                if (parsed) {
                    if (Date.now() - parsed.fetchedAt < CACHE_DURATION) {
                        console.log('[MarketContext] Using cached data');
                        setMarketData(parsed);
                        setLoading(false);
                        setLastFetch(parsed.fetchedAt);
                        return;
                    }
                }
            } catch {
                console.warn('[MarketContext] Cache read failed');
            }
        }

        setLoading(true);
        setError(null);

        try {
            const data = await fetchAllMarketData();
            setMarketData(data);
            setLastFetch(Date.now());

            // Save to cache
            try {
                await idbSet(CACHE_KEY, data);
                localStorage.setItem(CACHE_KEY, JSON.stringify(data));
            } catch {
                console.warn('[MarketContext] Failed to save to cache');
            }

            console.log('[MarketContext] ✅ Market data loaded');
        } catch (err) {
            console.error('[MarketContext] ❌ Failed to load market data:', err);

            // Fallback to stale cache (up to 4 hours)
            try {
                let parsed = await idbGet(CACHE_KEY);
                if (!parsed) {
                    const cached = localStorage.getItem(CACHE_KEY);
                    if (cached) parsed = JSON.parse(cached);
                }

                if (parsed) {
                    const age = Date.now() - parsed.fetchedAt;

                    console.log(`[MarketContext] Using stale cache due to fetch error (Age: ${(age/60000).toFixed(0)}m)`);
                    setMarketData(parsed);
                    setLastFetch(parsed.fetchedAt);

                    if (age > 4 * 60 * 60 * 1000) {
                        setError('Network error. Data is expired (>4h).');
                    } else {
                        setError('Network error. Showing cached data.');
                    }
                } else {
                    // Try ultimate fallback: Static JSON (generated by backend script)
                    try {
                        const resp = await fetch('/data/market_snapshot.json');
                        if (resp.ok) {
                            const snapshot = await resp.json();
                            if (snapshot && snapshot.indices && snapshot.indices.length > 0) {
                                console.log('[MarketContext] Using static snapshot fallback');
                                setMarketData(snapshot);
                                const generated = snapshot.generatedAt || snapshot.generated_at;
                                setLastFetch(generated ? new Date(generated).getTime() : Date.now());
                                setError('Using offline snapshot (Live data failed)');
                                return;
                            }
                        }
                    } catch (staticErr) {
                        console.warn('Static fallback failed', staticErr);
                    }
                    setError(err.message);
                }
            } catch {
                setError(err.message);
            }
        } finally {
            setLoading(false);
        }
    }, []);

    // REMOVED: auto-load on mount — market data now fetched lazily
    const ensureBoot = useCallback(() => {
        if (!booted) {
            setBooted(true);
            loadMarketData();  // loadMarketData already sets loading:true internally
        }
    }, [booted, loadMarketData]);

    // Web Worker for Price Alerts
    useEffect(() => {
        if (marketData && marketData.indices) {
            // Note: in a real app, thresholds would come from user settings
            const dummyThresholds = {
                'NIFTY 50': { upper: 30000, lower: 10000 }
            };

            const worker = new Worker(new URL('../workers/priceAlertWorker.js', import.meta.url), { type: 'module' });

            worker.onmessage = (event) => {
                const { type, payload } = event.data;
                if (type === 'ALERTS_GENERATED' && payload.length > 0) {
                    console.log('[MarketContext] 🚨 Price Alerts:', payload);
                    // Could dispatch to a toast notification system here
                }
            };

            worker.postMessage({
                type: 'CHECK_PRICES',
                payload: { marketData, thresholds: dummyThresholds }
            });

            return () => worker.terminate();
        }
    }, [marketData]);

    const refreshMarket = useCallback(() => {
        return loadMarketData(true);
    }, [loadMarketData]);

    return (
        <MarketContext.Provider value={{
            marketData,
            loading: booted ? loading : true,  // Show spinner until booted (audit v3 fix)
            error,
            lastFetch,
            refreshMarket,
            ensureBoot,
            booted
        }}>
            {children}
        </MarketContext.Provider>
    );
}

export function useMarket() {
    const context = useContext(MarketContext);
    if (!context) {
        throw new Error('useMarket must be used within MarketProvider');
    }
    return context;
}
